@startuml
'https://plantuml.com/class-diagram

class Main{
-UI ui
}

class Player {
-String playerName
+String getName()
}

class Team {
-String teamName
-int teamTournamentScore
-int teamGoalScore
-boolean lostLastMatch
-Player[] players
+setPlayers()
+addPlayer()
+removePlayer()
+String toString()
}

class Match{
-Team[] teams
-int matchGoalScore;
-String matchName;
}

abstract Tournament {
-String tournamentName
-Team[] teams
-Match[] matches
+{abstract}winnerTeamNewTotalScore()
+{abstract}loserTeamNewTotalScore()
+{abstract}determineWinnerTeamOutcome()
+{abstract}determineLoserTeamOutcome()
+{abstract}ArrangeMatches()
+getTournamentName()
+getTeam()
+getMatches()
+String toString()
}

class KnockoutTournament{
-int winnerTeamMatchScore;
-int loserTeamMatchScore
-int goalScore = winnerTeamMatchScore - loserTeamMatchScore;
+winnerTeamNewTotalScore()
+loserTeamNewTotalScore()
+determineWinnerTeamOutcome()
+determineLoserTeamOutcome()
+ArrangeMatches()
}

class GroupTournament{
-Team[] ScoreBoard
+winnerTeamNewTotalScore()
+loserTeamNewTotalScore()
+determineWinnerTeamOutcome()
+determineLoserTeamOutcome()
+ArrangeMatches()
}

class UI {
-String tournamentType
-String teamName
-Scanner sc
-String[] playerNames
-Player player
-Team team
+createPlayer()
+createTeam()
+getMatchSchedule()
+getTeamPlacement()
+getNextMatch()
}

class IO {
-String getData
-FileWriter writeFile
-File teamFile
-Scanner sc
-String teamFileName
-String matchData
+addPointsToTeam()
+readFromFile()
}


UI o-- Tournament
UI o-- IO
Tournament *-- "8" Match
Tournament *-- Team
Match o-- "2" Team
Team o-- "2..*" Player
Tournament <|-- KnockoutTournament
Tournament <|-- GroupTournament
Main o-- UI
@enduml