@startuml
'https://plantuml.com/class-diagram

class Player {
-String playerName
-<ArrayList> addPlayer
}

class Team {
+String teamName
+Player players
+AddMemberToTeam()
+RemoveMemberFromTeam()
+String toString()
}

class Match{
-int {static} IDCounter
+int matchID
+addPoints()
+getPoints()
+String toString()
}

class Tournament {
+Player players
+Team teams
+Match matches
+ArrangeMatches()
+String toString()
}

class TournamentOrganizer {
+createTeam()
+getMatchSchedule()
+getTeamPlacement()
+getNextMatch()
}

Tournament o-- "1" TournamentOrganizer
Tournament *-- "8" Match
Tournament *-- Player
Tournament *-- Team
Match o-- "2" Team
Team o-- "2..*" Player

@enduml